name: QMK Build

on: 
  workflow_dispatch:
    inputs:
      make-target:
        type: string
        default: "pegasushoof:ocodo"

jobs:
  build:
    name: qmk_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build ${{ github.event.input.make-target }}"
        run: |
          sudo apt install gcc-avr avr-libc
          make ${{ github.event.input.make-target }}

      - name: Upload a Firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware
          path: build          

  

