name: QMK Build

on: 
  workflow_dispatch:
    inputs:
      make-target:
        type: string
        default: "pegasushoof:ocodo"

jobs:
  build:
    name: qmk_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build ${{ github.event.inputs.make-target }}"
        run: |
          sudo apt install gcc-avr avr-libc
          make ${{ github.event.inputs.make-target }}
          echo "FIRMWARE=$("${{ github.event.inputs.make-target }}" | tr ':' '_')" >> $GITHUB_ENV

      - name: Upload a Firmware
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.FIRMWARE }}.hex"
          path: ./.build
