name: QMK Build

on: 
  workflow_dispatch:
    inputs:
      make-target:
        type: string
        default: "pegasushoof:ocodo"

jobs:
  build:
    name: qmk_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build ${{ github.event.inputs.make-target }}"
        run: |
          sudo apt install gcc-avr avr-libc
          make ${{ github.event.inputs.make-target }}
          echo "firmware=$("${{ github.event.inputs.make-target }}" | tr ':' '_')" >> $

      - name: Upload a Firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "${{ env.firmware }}*"
          path: ./.build
